name: Update WPT

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update-wpt:
    name: Update WPT
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          sparse-checkout: |
            # Burada yalnızca dahil edilmesi gereken dizinleri listeleyin
            src/
            docs/
      - name: Clone WPT Repository
        uses: actions/checkout@v4
        with:
          repository: web-platform-tests/wpt
          path: test/fixtures/wpt
          sparse-checkout: |
            common/ eventsource/ fetch/ interfaces/ mimesniff/ resources/ service-workers/ storage/ websockets/ xhr/ LICENSE.md
          persist-credentials: true
      - name: Move WPT Files
        run: |
          rm -rf test/fixtures/wpt/.git
          echo "NEW_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Create Or Update Pull Request
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_USER_TOKEN }}
        with:
          author: Node.js GitHub Bot <github-bot@iojs.org>
          body: This is an automated update of the WPT to ${{ env.NEW_VERSION }}.
          branch: actions/update-wpt
          commit-message: 'test: update WPT to ${{ env.NEW_VERSION }}'
          labels: test
          title: 'test: update WPT to ${{ env.NEW_VERSION }}'
          update-pull-request-title-and-body: true
